// app/blog/page.tsx
import { getSortedPosts } from "@/lib/blog";
import { format } from "date-fns";
import Link from "next/link";
import Image from "next/image";

export default async function BlogPage() {
  const posts = await getSortedPosts();

  return (
    <div className="container mx-auto py-8 md:py-12 lg:py-24">
      <div className="mx-auto max-w-[64rem]">
        <h1 className="font-heading text-4xl md:text-6xl mb-8">Blog</h1>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {posts.map((post) => (
            <article key={post.slug} className="group relative">
              <Link href={`/blog/${post.slug}`}>
                <div className="relative overflow-hidden rounded-xl border bg-background p-2 transition-all duration-300 hover:shadow-xl hover:shadow-primary/10 hover:-translate-y-1">
                  {post.cover && (
                    <div className="relative h-48 w-full mb-4 overflow-hidden rounded-lg">
                      <Image
                        src={post.cover}
                        alt={post.title}
                        fill
                        className="object-cover"
                      />
                    </div>
                  )}
                  <div className="space-y-3 p-4">
                    <h2 className="font-heading text-xl line-clamp-2">{post.title}</h2>
                    <div className="text-sm text-muted-foreground">
                      {format(new Date(post.date), "MMMM d, yyyy")}
                    </div>
                    {post.excerpt && (
                      <p className="text-muted-foreground line-clamp-3">{post.excerpt}</p>
                    )}
                    {post.tags && (
                      <div className="flex flex-wrap gap-2">
                        {post.tags.map((tag) => (
                          <span
                            key={tag}
                            className="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </Link>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/routes/blog/+page.svelte
<script>
	export let data;
</script>

<h1 class="font-bold pt-4 pb-8">Blog</h1>
<div class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
	{#each data.posts as post}
		<a class="card bg-initial card-hover overflow-hidden mx-auto lg:mx-4 my-4" href={post.path}>
			<header>
				<img src={post.meta.cover} class="h-48 w-full object-cover" alt="Post" />
			</header>
			<div class="p-4 space-y-4">
				<h4 data-toc-ignore="" class="font-bold">{post.meta.title}</h4>
				<article>
					<p>
						{post.meta.excerpt}
					</p>
				</article>
			</div>
			<footer>
				<hr class="opacity-50" />
				<div class="p-4 flex justify-end items-center space-x-4">
					<figure
						class="avatar flex aspect-square text-surface-50 font-semibold justify-center items-center overflow-hidden isolate bg-surface-400-500-token w-8 rounded-full"
						data-testid="avatar">
						<img
							class="avatar-image w-full h-full object-cover"
							src="/images/avatar-thumb.png"
							alt=""
							style="" />
					</figure>
					<div class="flex-auto flex justify-between items-center align">
						<h6 class="font-bold">By Jordan Harrison</h6>
						<small>On {post.meta.date}</small>
					</div>
				</div>
			</footer>
		</a>
	{/each}
</div>
